### PR TITLE
Add JSON output.

### PR DESCRIPTION
**Pull request by lpereira**
JSON output is useful if you want to parse weighttp's output and feed it into a program that will, say, plot the results.

### CODE REVIEW

**Comment by gstrauss** [comment]
I have an experimental branch at https://github.com/gstrauss/weighttp/tree/rewrite which is a nearly complete rewrite of weighttp.  The output is JSON that is similar, but not quite the same, as you have in your patch here.  Use with `weighttp -q` to quiet other (non-JSON) diagnostic output to stdout.

Separately, in my rewrite, I did not find a measurable improvement in performance using tcmalloc, though that is probably due to performing all memory allocations at startup, with the majority done per-thread for exclusive use by each thread.

Feedback appreciated.

**Comment by lpereira** [comment]
@gstrauss Pipelining support as well. Good stuff, I'll give it a try.

**Comment by gstrauss** [comment]
@lpereira: Have you had a chance to give https://github.com/gstrauss/weighttp/tree/rewrite a whirl?  Instead of promoting that branch to weighttp-0.5, I think it may be better to bump major version and call it weighttp-1.0.  Thoughts?

**Comment by lpereira** [comment]
I did, @gstrauss. It works pretty well. I'm not using `wrk` with a Lua script to benchmark pipelined requests anymore.

It seems that lighttpd has been abandoned; nobody has commented here for a while, not sure if this issue tracker is even monitored. Maybe you want to take over weighttp, or call it something else?

**Comment by gstrauss** [comment]
Thanks for the quick feedback!

Fret not! :)  Yes, this issue tracker is being monitored.  I have been working with the current maintainers over the past few months and am now helping to maintain weighttp and lighttpd.

Based on your comment, I think that you're suggesting that https://github.com/gstrauss/weighttp/tree/rewrite be promoted to weighttp-1.0.

**Comment by lpereira** [comment]
Good to hear the project isn't dead and the maintainers are cool with your improved version! Yes, I'd suggest to promote your rewrite tree as weighttp-1.0.

**Pull request closed without merging**
